exclude: ^(translations/|.*\.css|.*\.svg|octoprint_wled/static/webfonts|versioneer.py|octoprint_wled/_version.py|node_modules|octoprint_wled/static/dist)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]
  - repo: https://github.com/OctoPrint/codemods
    rev: "0.6.2"
    hooks:
      - id: codemod_batch
        args:
          [
              "--check",
              "not_in",
              "--check",
              "detect_past_builtins_imports"
          ]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.9.0
  #   hooks:
  #     - id: eslint
  #       additional_dependencies:
  #         - eslint@8.9.0
  #         - eslint-config-standard@17.0.0-1
